'use client';

import React, { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { Download, Crop } from 'lucide-react';
import { BASEMAPS, isBasemapAvailable } from '@/lib/basemaps';

// A Leaflet layer generated by L.geoJSON() carries the source GeoJSON feature it
// was built from - used by the export flow to find the selected boundary's exact
// geometry/bounds regardless of which admin level (province..village) it came from.
type BoundaryLayer = L.Layer & { feature?: GeoJSON.Feature; getBounds?: () => L.LatLngBounds };

interface InteractiveMapProps {
  onSelectVillage: (village: any) => void;
  onMapClick: (lat: number, lng: number) => void;
  onViewportChange: (viewport: {
    minLng: number;
    minLat: number;
    maxLng: number;
    maxLat: number;
    zoom: number;
  }) => void;
  boundaryGeoJson: any;
  parentBoundaryGeoJson: any;
  activeBasemap: string;
  sentinelYear: string;
}

export default function InteractiveMap({
  onSelectVillage,
  onMapClick,
  onViewportChange,
  boundaryGeoJson,
  parentBoundaryGeoJson,
  activeBasemap,
  sentinelYear
}: InteractiveMapProps) {
  const mapContainerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<L.Map | null>(null);
  const [isMapReady, setIsMapReady] = useState(false);

  // Basemap Tile Layers - one entry per available BASEMAPS definition, keyed by id
  const tileLayersRef = useRef<Map<string, L.TileLayer>>(new Map());

  // Layer References
  const countryLayerRef = useRef<L.GeoJSON | null>(null);
  const boundaryLayerRef = useRef<L.GeoJSON | null>(null);
  const parentBoundaryLayerRef = useRef<L.GeoJSON | null>(null);

  // Last-clicked boundary feature (province/district/sector/cell/village - whichever
  // level is active) kept around purely so "Export Selected" can crop/clip to it
  const selectedExportLayerRef = useRef<L.Layer | null>(null);
  const [hasSelectedExportLayer, setHasSelectedExportLayer] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  // Initialize Map
  useEffect(() => {
    if (!mapContainerRef.current || mapRef.current) return;

    // Create Map centered in Rwanda with Canvas rendering enabled for 10x vector performance
    const map = L.map(mapContainerRef.current, {
      center: [-1.9403, 29.8739],
      zoom: 9.3,
      minZoom: 8,
      maxZoom: 18,
      zoomControl: false,
      zoomSnap: 0.1,
      zoomDelta: 0.5, // Smaller wheel/keyboard zoom steps feel smoother than a full level at a time
      wheelDebounceTime: 100, // Coalesce fast scroll-wheel ticks so intermediate frames don't each trigger a boundary refetch/rebuild
      wheelPxPerZoomLevel: 100, // Require more scroll distance per zoom level for finer, less jumpy zoom steps
      inertia: true,
      preferCanvas: true, // Force all vector layers (not just the default renderer) onto canvas for cheaper repaint
      renderer: L.canvas({ padding: 0.5 }) // Butter-smooth canvas drawing instead of heavy SVG path DOM nodes; extra padding avoids visible redraw pop-in while panning
    });

    mapRef.current = map;

    // Add Zoom Control at bottom right
    L.control.zoom({ position: 'bottomright' }).addTo(map);

    // Shared tuning applied to every tile layer: avoids fetching/painting new tiles
    // mid zoom-animation (the main source of visible stutter) and keeps a wider
    // buffer of pre-rendered offscreen tiles so panning/zooming doesn't reveal blanks.
    const tileTuning: L.TileLayerOptions = {
      maxZoom: 18,
      updateWhenZooming: false,
      keepBuffer: 4,
      updateInterval: 150,
      // Every provider in BASEMAPS serves tiles with Access-Control-Allow-Origin: *,
      // so requesting them in CORS mode keeps the tile <img>s readable by <canvas> -
      // required for the PNG export below, which otherwise gets a tainted-canvas
      // SecurityError on save.
      crossOrigin: true
    };

    // Build one tile layer per available basemap definition. Providers missing a
    // required API key (see BASEMAPS[].requiresEnvVar) are skipped entirely instead
    // of being wired up with a URL that would just 401/404.
    for (const bm of BASEMAPS) {
      if (!isBasemapAvailable(bm)) continue;
      const layer = L.tileLayer(bm.buildUrl({ year: sentinelYear, date: '' }), {
        ...tileTuning,
        maxZoom: bm.maxZoom ?? tileTuning.maxZoom,
        ...(bm.subdomains ? { subdomains: bm.subdomains } : {}),
        attribution: bm.attribution
      });
      tileLayersRef.current.set(bm.id, layer);
    }

    // Set initial basemap
    tileLayersRef.current.get(activeBasemap)?.addTo(map);

    // Load static Country Boundary outline
    fetch('/data/country boundary.geojson')
      .then(res => res.json())
      .then(data => {
        if (!mapRef.current) return;
        countryLayerRef.current = L.geoJSON(data, {
          style: {
            color: '#ffffff',
            weight: 1.5,
            opacity: 0.25,
            fillOpacity: 0.0,
            dashArray: '4,4'
          },
          interactive: false
        }).addTo(mapRef.current);
      })
      .catch(err => console.error('Failed to load Rwanda country outline', err));

    // Monitor viewport changes
    const updateViewport = () => {
      const zoom = map.getZoom();
      const bounds = map.getBounds();
      onViewportChange({
        minLng: bounds.getWest(),
        minLat: bounds.getSouth(),
        maxLng: bounds.getEast(),
        maxLat: bounds.getNorth(),
        zoom: zoom
      });
    };

    map.on('moveend', updateViewport);

    // Add map click listener to resolve coordinates hierarchically
    const handleClick = (e: L.LeafletMouseEvent) => {
      onMapClick(e.latlng.lat, e.latlng.lng);
    };
    map.on('click', handleClick);

    // Trigger initial fetch. Guarded by `cancelled` (flipped in cleanup) because in
    // React Strict Mode dev double-invokes this effect - mount, cleanup, mount again -
    // and without the guard this timer can fire after `map.remove()` already ran,
    // calling map.getBounds() on a torn-down map (crashes reading `_leaflet_pos`
    // off its now-detached pane).
    let cancelled = false;
    const initialFetchTimer = setTimeout(() => {
      if (cancelled) return;
      updateViewport();
      setIsMapReady(true);
    }, 200);

    return () => {
      cancelled = true;
      clearTimeout(initialFetchTimer);
      map.off('moveend', updateViewport);
      map.off('click', handleClick);
      map.remove();
      mapRef.current = null;
    };
  }, []);

  // -------------------------------------------------------------
  // DYNAMIC BASEMAP CONTROLLER
  // -------------------------------------------------------------
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;

    // Remove whichever tile layer is currently on the map
    for (const layer of tileLayersRef.current.values()) {
      if (map.hasLayer(layer)) map.removeLayer(layer);
    }

    // Refresh the URL of every time-aware layer (e.g. Sentinel-2's yearly mosaic)
    // in case the selected year/date changed, then add the active one
    for (const bm of BASEMAPS) {
      if (!bm.supportsYear && !bm.supportsDate) continue;
      const layer = tileLayersRef.current.get(bm.id);
      layer?.setUrl(bm.buildUrl({ year: sentinelYear, date: '' }));
    }

    tileLayersRef.current.get(activeBasemap)?.addTo(map);
  }, [activeBasemap, sentinelYear]);

  // -------------------------------------------------------------
  // RENDER DYNAMIC BOUNDARIES BASED ON ACTIVE LAYER DATA
  // -------------------------------------------------------------
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !isMapReady) return;

    // Clean up previous active boundary layer
    if (boundaryLayerRef.current) {
      map.removeLayer(boundaryLayerRef.current);
      boundaryLayerRef.current = null;
    }

    // The previously selected feature belongs to whatever boundary set was on the
    // map before - once that set is replaced (pan/zoom refetch) it no longer
    // matches what's rendered, so drop it rather than exporting a stale cutout.
    selectedExportLayerRef.current = null;
    setHasSelectedExportLayer(false);

    if (!boundaryGeoJson || !boundaryGeoJson.features || boundaryGeoJson.features.length === 0) return;

    // Detect layer type from feature properties
    const sample = boundaryGeoJson.features[0].properties;
    const isVillage = 'village_id' in sample;
    const isCell = 'cell_id' in sample && !isVillage;
    const isSector = 'sector_id' in sample && !isCell && !isVillage;
    const isDistrict = 'district_i' in sample && !isSector && !isCell && !isVillage;
    const isProvince = !isDistrict && !isSector && !isCell && !isVillage;

    const isSatellite = activeBasemap === 'esri' || activeBasemap === 'sentinel2' || activeBasemap === 'blackmarble';

    // Custom stylings based on Rwanda Flag Colors (Active layer has lighter weight for contextual comparison)
    const style = (feature: any) => {
      if (isProvince) {
        return {
          color: '#00A3E0', // Flag Blue
          weight: 1.5,
          opacity: 0.6,
          fillColor: '#00A3E0',
          fillOpacity: 0.03
        };
      } else if (isDistrict) {
        return {
          color: '#FCD116', // Flag Yellow
          weight: 1.2,
          opacity: 0.55,
          fillColor: '#FCD116',
          fillOpacity: 0.03
        };
      } else if (isSector) {
        return {
          color: '#FCD116', // Flag Yellow
          weight: 1.0,
          opacity: 0.5,
          fillColor: '#FCD116',
          fillOpacity: 0.02
        };
      } else if (isCell) {
        return {
          color: '#FCD116', // Flag Yellow
          weight: 0.8,
          opacity: 0.45,
          fillColor: '#FCD116',
          fillOpacity: 0.02
        };
      } else {
        // Villages
        return {
          color: '#FCD116', // Flag Yellow for Villages
          weight: isSatellite ? 1.4 : 0.6, 
          opacity: isSatellite ? 0.8 : 0.4, 
          fillColor: '#FCD116',
          fillOpacity: isSatellite ? 0.05 : 0.01
        };
      }
    };

    // Hover events and popups
    const onEachFeature = (feature: any, layer: L.Layer) => {
      layer.on({
        mouseover: (e) => {
          const l = e.target;
          // Set glow highlights: Blue for yellow boundaries, Yellow for blue boundaries
          l.setStyle({
            color: isProvince ? '#FCD116' : '#00A3E0',
            weight: isProvince ? 3.0 : 2.0,
            opacity: 1.0,
            fillColor: isProvince ? '#FCD116' : '#00A3E0',
            fillOpacity: 0.15
          });
          if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
            l.bringToFront();
          }
        },
        mouseout: (e) => {
          if (boundaryLayerRef.current) {
            boundaryLayerRef.current.resetStyle(e.target);
          }
        },
        click: (e) => {
          if (e.originalEvent) {
            L.DomEvent.stopPropagation(e.originalEvent);
          }
          selectedExportLayerRef.current = e.target;
          setHasSelectedExportLayer(true);
          onSelectVillage(feature.properties);
        }
      });

      // Bind dynamic descriptive tooltips lazily - passing a function defers building
      // the HTML string until the tooltip actually opens, instead of doing it for
      // every one of the (potentially thousands of) features up front on layer creation
      layer.bindTooltip(
        () => {
          const props = feature.properties;
          let tooltipContent = '';
          if (isProvince) {
            tooltipContent = `<strong class="text-[#00A3E0] text-xs font-semibold block">${props.province}</strong><span class="text-[9px] text-gray-400 block">Province Level</span>`;
          } else if (isDistrict) {
            tooltipContent = `<strong class="text-[#FCD116] text-xs font-semibold block">${props.district} District</strong><span class="text-[10px] text-gray-300 block">${props.province}</span>`;
          } else if (isSector) {
            tooltipContent = `<strong class="text-[#FCD116] text-xs font-semibold block">${props.sector} Sector</strong><span class="text-[10px] text-gray-300 block">${props.district} District</span>`;
          } else if (isCell) {
            tooltipContent = `<strong class="text-[#FCD116] text-xs font-semibold block">${props.cell} Cell</strong><span class="text-[10px] text-gray-300 block">${props.sector} Sector</span>`;
          } else {
            tooltipContent = `<strong class="text-[#FCD116] text-xs font-semibold block">${props.village}</strong><span class="text-[10px] text-gray-300 block">${props.cell} Cell, ${props.sector} Sector</span>`;
          }
          return `<div class="text-left font-sans">${tooltipContent}</div>`;
        },
        { sticky: true, className: 'leaflet-tooltip' }
      );
    };

    // Render GeoJSON to map optimized for Canvas rendering
    boundaryLayerRef.current = L.geoJSON(boundaryGeoJson, {
      style,
      onEachFeature
    }).addTo(map);

    // Keep active layer on top of parent contextual boundaries
    if (boundaryLayerRef.current && parentBoundaryLayerRef.current) {
      boundaryLayerRef.current.bringToFront();
    }

  }, [boundaryGeoJson, isMapReady]);

  // -------------------------------------------------------------
  // RENDER PARENT BOUNDARIES (UPPER OUTLINES FOR CONTEXT)
  // -------------------------------------------------------------
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !isMapReady) return;

    // Clean up previous parent outline layer
    if (parentBoundaryLayerRef.current) {
      map.removeLayer(parentBoundaryLayerRef.current);
      parentBoundaryLayerRef.current = null;
    }

    if (!parentBoundaryGeoJson || !parentBoundaryGeoJson.features || parentBoundaryGeoJson.features.length === 0) return;

    const sample = parentBoundaryGeoJson.features[0].properties;
    const isProvince = !('district_i' in sample);

    const isSatellite = activeBasemap === 'esri' || activeBasemap === 'sentinel2' || activeBasemap === 'blackmarble';

    // Thicker, bolder Flag Blue outlines for parent boundaries to provide context
    const style = {
      color: '#00A3E0', // Flag Blue
      weight: isSatellite ? 3.0 : 2.5, // Thicker outline
      opacity: isSatellite ? 0.95 : 0.85,
      fillColor: 'none',
      fillOpacity: 0.0,
      dashArray: isProvince ? undefined : '8, 8' // Dashed for sectors/districts
    };

    // Render GeoJSON for non-interactive background vectors
    parentBoundaryLayerRef.current = L.geoJSON(parentBoundaryGeoJson, {
      style,
      interactive: false
    }).addTo(map);

    // Ensure active boundary layer stays on top for interactive events
    if (boundaryLayerRef.current) {
      boundaryLayerRef.current.bringToFront();
    }

  }, [parentBoundaryGeoJson, isMapReady]);

  // -------------------------------------------------------------
  // EXPORT MAP TO PNG
  // -------------------------------------------------------------
  // Right-click -> "Save image as" only ever grabs ONE dom element under the
  // cursor - either a single satellite tile <img>, or the transparent <canvas>
  // that the boundary borders are drawn on (preferCanvas: true) - never both.
  // That's why saved images come back with borders on a blank/white background.
  // This flattens every currently-visible tile <img> plus the vector overlay
  // canvas(es) into one offscreen canvas, in the same on-screen order, and
  // downloads that as a single PNG.
  //
  // mode: 'view' exports the full current viewport (background + all borders).
  // mode: 'selected' clips/crops to the last-clicked boundary (cell, sector,
  // district, village, whichever level is active) so only that shape - border
  // plus the satellite background inside it - is visible, the rest transparent.
  //
  // For 'selected', quality tracks whatever zoom level the map happened to be at
  // when exported - so exporting while zoomed out just upscales blurry, low-res
  // tiles. Instead, first fly the map in to the tightest zoom that still fits the
  // whole boundary on screen (capped at the basemap's maxZoom) - bringing an
  // off-screen selection into view in the process - wait for those high-res tiles
  // to finish loading, capture, then fly back to wherever the user was.
  const waitForMapIdle = (map: L.Map, tileLayer?: L.TileLayer): Promise<void> => {
    return new Promise((resolve) => {
      let settled = false;
      const finish = () => {
        if (settled) return;
        settled = true;
        resolve();
      };

      const onMoveEnd = () => {
        const loading = (tileLayer as (L.TileLayer & { isLoading?: () => boolean }) | undefined)?.isLoading?.();
        if (tileLayer && loading) {
          const onLoad = () => {
            tileLayer.off('load', onLoad);
            finish();
          };
          tileLayer.on('load', onLoad);
          setTimeout(finish, 6000); // fallback in case a tile stalls/fails to ever fire 'load'
        } else {
          finish();
        }
      };

      map.once('moveend', onMoveEnd);
      setTimeout(finish, 6000); // fallback in case moveend itself never fires
    });
  };

  const exportMapImage = async (mode: 'view' | 'selected') => {
    const map = mapRef.current;
    const container = mapContainerRef.current;
    if (!map || !container) return;

    let layer: BoundaryLayer | null = null;
    let bounds: L.LatLngBounds | null = null;

    if (mode === 'selected') {
      layer = selectedExportLayerRef.current as BoundaryLayer | null;
      if (!layer || !layer.feature || !layer.getBounds) {
        alert('Click a boundary on the map first (cell, sector, district or village) to select it for export.');
        return;
      }
      bounds = layer.getBounds();
    }

    setIsExporting(true);

    // If exporting a selection, zoom/pan in to the highest-resolution view that
    // still fits the whole shape on screen (bringing it on-screen first if it
    // was off-screen), and remember how to fly back once we're done.
    let restoreView: (() => void) | null = null;
    if (mode === 'selected' && bounds) {
      const activeTileLayer = tileLayersRef.current.get(activeBasemap);
      const maxZoom = activeTileLayer?.options.maxZoom ?? 18;
      const idealZoom = Math.min(map.getBoundsZoom(bounds), maxZoom);
      const alreadyGoodView = map.getZoom() >= idealZoom && map.getBounds().contains(bounds);

      if (!alreadyGoodView) {
        const originalCenter = map.getCenter();
        const originalZoom = map.getZoom();
        restoreView = () => map.setView(originalCenter, originalZoom, { animate: false });

        const idle = waitForMapIdle(map, activeTileLayer);
        map.fitBounds(bounds, { maxZoom, animate: false, padding: [60, 60] });
        await idle;
      }
    }

    const containerRect = container.getBoundingClientRect();

    let offsetX = 0;
    let offsetY = 0;
    let outW = containerRect.width;
    let outH = containerRect.height;
    let clipPath: Path2D | null = null;

    if (mode === 'selected' && layer && bounds) {
      const nw = map.latLngToContainerPoint(bounds.getNorthWest());
      const se = map.latLngToContainerPoint(bounds.getSouthEast());
      const pad = 24;
      offsetX = Math.max(0, nw.x - pad);
      offsetY = Math.max(0, nw.y - pad);
      outW = Math.min(containerRect.width, se.x + pad) - offsetX;
      outH = Math.min(containerRect.height, se.y + pad) - offsetY;

      if (outW <= 0 || outH <= 0) {
        alert('Could not fit the selected boundary on screen to export it - try again after panning/zooming manually.');
        restoreView?.();
        setIsExporting(false);
        return;
      }

      // Build the exact polygon (holes included) as a canvas Path2D in current
      // screen-pixel space, so clipping matches what is actually drawn on the map.
      const path = new Path2D();
      const addRing = (ring: GeoJSON.Position[]) => {
        ring.forEach((coord, i) => {
          const pt = map.latLngToContainerPoint([coord[1], coord[0]]);
          if (i === 0) path.moveTo(pt.x, pt.y);
          else path.lineTo(pt.x, pt.y);
        });
        path.closePath();
      };
      const geom = layer.feature!.geometry;
      if (geom.type === 'Polygon') {
        geom.coordinates.forEach(addRing);
      } else if (geom.type === 'MultiPolygon') {
        geom.coordinates.forEach((poly) => poly.forEach(addRing));
      }
      clipPath = path;
    }

    try {
      const scale = window.devicePixelRatio || 1;
      const canvas = document.createElement('canvas');
      canvas.width = Math.max(1, Math.round(outW * scale));
      canvas.height = Math.max(1, Math.round(outH * scale));
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      ctx.scale(scale, scale);
      ctx.translate(-offsetX, -offsetY);

      if (clipPath) {
        ctx.save();
        ctx.clip(clipPath, 'evenodd');
      }

      // 1. Draw every loaded satellite/basemap tile image at its real on-screen position
      const tileImgs = Array.from(container.querySelectorAll('img.leaflet-tile-loaded')) as HTMLImageElement[];
      for (const img of tileImgs) {
        if (!img.complete || img.naturalWidth === 0) continue;
        const r = img.getBoundingClientRect();
        try {
          ctx.drawImage(img, r.left - containerRect.left, r.top - containerRect.top, r.width, r.height);
        } catch {
          // A tile that slipped through without CORS headers would taint the
          // canvas here - skip it rather than aborting the whole export.
        }
      }

      if (clipPath) {
        ctx.restore(); // stop clipping before the border stroke so it stays crisp/full-weight
      }

      // 2. Draw the vector boundary canvas(es) on top, same as they appear on the map
      const overlayCanvases = Array.from(container.querySelectorAll('canvas')) as HTMLCanvasElement[];
      for (const c of overlayCanvases) {
        const r = c.getBoundingClientRect();
        ctx.drawImage(c, r.left - containerRect.left, r.top - containerRect.top, r.width, r.height);
      }

      // 3. For a single-boundary export, re-stroke its outline boldly so the
      // cutout edge reads clearly against the transparent surroundings
      if (clipPath) {
        ctx.save();
        ctx.lineJoin = 'round';
        ctx.strokeStyle = '#FCD116';
        ctx.lineWidth = 3;
        ctx.stroke(clipPath);
        ctx.restore();
      }

      canvas.toBlob((blob) => {
        if (!blob) {
          restoreView?.();
          setIsExporting(false);
          return;
        }
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = mode === 'selected' ? `boundary-export-${Date.now()}.png` : `map-view-${Date.now()}.png`;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(url);
        restoreView?.();
        setIsExporting(false);
      }, 'image/png');
    } catch (err) {
      console.error('Map export failed', err);
      alert('Export failed - this is usually a tainted-canvas error from a tile provider without CORS headers.');
      restoreView?.();
      setIsExporting(false);
    }
  };

  return (
    <div className="w-full h-full relative z-0">
      {/* Map Container Element */}
      <div
        ref={mapContainerRef}
        className="w-full h-full"
        style={{ background: '#060709' }}
      />

      {/* Export Controls */}
      <div className="absolute top-4 right-4 z-[1000] flex flex-col gap-2 pointer-events-auto">
        <button
          onClick={() => exportMapImage('view')}
          disabled={isExporting}
          title="Download the current map view (satellite background + boundaries) as one PNG"
          className="glass-panel flex items-center gap-2 px-3 py-2 text-xs font-semibold text-[#f0f2f5] hover:text-[#00A3E0] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          <Download className="w-3.5 h-3.5" />
          Export View
        </button>
        <button
          onClick={() => exportMapImage('selected')}
          disabled={isExporting || !hasSelectedExportLayer}
          title="Download only the last-clicked boundary (cell/sector/district/village), cropped and clipped to its shape"
          className="glass-panel flex items-center gap-2 px-3 py-2 text-xs font-semibold text-[#f0f2f5] hover:text-[#FCD116] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          <Crop className="w-3.5 h-3.5" />
          Export Selected
        </button>
      </div>
    </div>
  );
}
